### ISSUE TITLE
Plasflow running problem

### ISSUE THREAD

**Issue by BurinkiWU** [smaegol/PlasFlow#12]
While I running the plasflow.py, I met some problems showing as following:

(plasflow) wzq:plasflow_output/ $ PlasFlow.py --input filtered_seameta_9.fasta --output seameta_19.plasflow.tsv                                                                                     [11:21:37]
Traceback (most recent call last):
  File "/home/wzq/.conda/envs/plasflow/bin/PlasFlow.py", line 50, in <module>
    from rpy2.robjects.packages import importr
  File "/home/wzq/.conda/envs/plasflow/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/home/wzq/.conda/envs/plasflow/lib/python3.5/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: libicuuc.so.54: cannot open shared object file: No such file or directory

How to fix it?

**Comment by BurinkiWU** [comment]
Hi,
Sure. There are listed as following,
wzq:plasflow_output/ $ conda list --show-channel-urls                                                                                                                                               [10:37:53]
# packages in environment at /home/wzq/miniconda3:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0                     mro_2    r
asn1crypto                0.24.0                   py35_0    defaults
binutils_impl_linux-64    2.28.1               had2808c_3    defaults
binutils_linux-64         7.2.0               had2808c_27    defaults
blas                      1.0                         mkl    defaults
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.12              h77bcde2_0    defaults
certifi                   2018.4.16                py35_0    conda-forge
cffi                      1.11.5           py35h9745a5d_0    defaults
chardet                   3.0.4            py35hb6e9ddf_1    defaults
conda                     4.5.4                    py35_0    conda-forge
conda-env                 2.6.0                h36134e3_1    defaults
cryptography              2.2.2            py35h14c3975_0    defaults
curl                      7.60.0                        0    conda-forge
fontconfig                2.13.0                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
fribidi                   1.0.2                h14c3975_0    defaults
gcc_impl_linux-64         7.2.0                habb00fd_3    defaults
gcc_linux-64              7.2.0               h550dcbe_27    defaults
gfortran_impl_linux-64    7.2.0                hdf63c60_3    defaults
gfortran_linux-64         7.2.0               h550dcbe_27    defaults
glib                      2.53.6               h5d9569c_2    defaults
graphite2                 1.3.11                        0    conda-forge
gxx_impl_linux-64         7.2.0                hdf63c60_3    defaults
gxx_linux-64              7.2.0               h550dcbe_27    defaults
harfbuzz                  1.7.6                hc5b324e_0    defaults
icu                       58.2                          0    conda-forge
idna                      2.7                      py35_0    defaults
intel-openmp              2018.0.3                      0    defaults
jinja2                    2.10                     py35_0    conda-forge
krb5                      1.14.6                        0    conda-forge
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 7.2.0                hdf63c60_3    defaults
libgfortran-ng            7.2.0                hdf63c60_3    defaults
libiconv                  1.15                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
libssh2                   1.8.0                         2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    defaults
libuuid                   1.0.3                         1    conda-forge
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.8                         0    conda-forge
markupsafe                1.0                      py35_0    conda-forge
mkl                       2018.0.3                      1    defaults
mkl_fft                   1.0.1            py35h3010b51_0    defaults
mkl_random                1.0.1            py35h629b387_0    defaults
mock                      2.0.0            py35h70ca42c_0    defaults
mro-base                  3.4.3                h1c2f66e_0    r
ncurses                   6.0                  h9df7e31_2    defaults
numpy                     1.14.5           py35hcd700cb_0    defaults
numpy-base                1.14.5           py35hdbf6ddf_0    defaults
openssl                   1.0.2o                        0    conda-forge
pango                     1.42.0               h377f3fa_0    defaults
pbr                       4.0.4                    py35_0    defaults
pcre                      8.41                          1    conda-forge
pip                       10.0.1                   py35_0    defaults
pixman                    0.34.0                        2    conda-forge
protobuf                  3.0.0b2                  py35_1    jjhelmus
pycosat                   0.6.3            py35h6b6bb97_0    defaults
pycparser                 2.18             py35h61b3040_1    defaults
pyopenssl                 18.0.0                   py35_0    defaults
pysocks                   1.6.8                    py35_0    defaults
python                    3.5.5                hc3d631a_3    defaults
r-assertthat              0.2.0           mro343h889e2dd_0    r
r-bh                      1.65.0_1        mro343h889e2dd_0    r
r-bindr                   0.1             mro343h889e2dd_0    r
r-bindrcpp                0.2             mro343h599a50d_0    r
r-bit                     1.1_12          mro343h086d26f_0    r
r-bit64                   0.9_7           mro343h086d26f_0    r
r-blob                    1.1.0           mro343h889e2dd_0    r
r-cli                     1.0.0           mro343h889e2dd_0    r
r-crayon                  1.3.4           mro343h889e2dd_0    r
r-dbi                     0.7             mro343h889e2dd_0    r
r-dbplyr                  1.1.0           mro343h889e2dd_0    r
r-digest                  0.6.13          mro343h086d26f_0    r
r-dplyr                   0.7.4           mro343h599a50d_0    r
r-glue                    1.2.0           mro343h086d26f_0    r
r-magrittr                1.5             mro343h889e2dd_0    r
r-memoise                 1.1.0           mro343h889e2dd_0    r
r-pillar                  1.0.1           mro343h889e2dd_0    r
r-pkgconfig               2.0.1           mro343h889e2dd_0    r
r-plogr                   0.1_1           mro343h889e2dd_0    r
r-purrr                   0.2.4           mro343h086d26f_0    r
r-r6                      2.2.2                  mro343_0    r
r-rcpp                    0.12.14         mro343h599a50d_0    r
r-rlang                   0.1.6           mro343h086d26f_0    r
r-rsqlite                 2.0             mro343h599a50d_0    r
r-tibble                  1.4.1           mro343h086d26f_0    r
r-utf8                    1.1.2           mro343h086d26f_0    r
readline                  7.0                  ha6073c6_4    defaults
requests                  2.14.2                   py35_0    defaults
rpy2                      2.9.1           py35mro343h14c3975_0    r
ruamel_yaml               0.15.40          py35h14c3975_2    defaults
setuptools                39.2.0                   py35_0    defaults
six                       1.11.0           py35h423b573_1    defaults
sqlite                    3.23.1               he433501_0    defaults
tensorflow                0.10.0rc0                py35_1    jjhelmus
tk                        8.6.7                hc745277_3    defaults
urllib3                   1.12                     py35_0    bioconda
wheel                     0.31.1                   py35_0    defaults
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                h55aa19d_2    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               ha838bed_2    defaults

**Comment by feilongzh** [comment]
> Hi,
> 
> could you post the output of:
> 
> `conda list --show-channel-urls`
> 
> run in your plasflow environment

I have the same question.How to deal with that?

**Comment by feilongzh** [comment]
> I have the same question.How to deal with that?



> While I running the plasflow.py, I met some problems showing as following:
> 
> (plasflow) wzq:plasflow_output/ $ PlasFlow.py --input filtered_seameta_9.fasta --output seameta_19.plasflow.tsv [11:21:37] Traceback (most recent call last): File "/home/wzq/.conda/envs/plasflow/bin/PlasFlow.py", line 50, in from rpy2.robjects.packages import importr File "/home/wzq/.conda/envs/plasflow/lib/python3.5/site-packages/rpy2/robjects/**init**.py", line 16, in import rpy2.rinterface as rinterface File "/home/wzq/.conda/envs/plasflow/lib/python3.5/site-packages/rpy2/rinterface/**init**.py", line 92, in from rpy2.rinterface._rinterface import (baseenv, ImportError: libicuuc.so.54: cannot open shared object file: No such file or directory
> 
> How to fix it?
I have the same question.How to deal with that?
