### ISSUE TITLE
tensorflow=0.10.0rc0 Install Failed

### ISSUE THREAD

**Issue by orctyr** [smaegol/PlasFlow#15]
Hi smaegol,

I use conda python=3.5 to install plasflow, everything is OK but tensorflow.
tensorflow=0.10.0rc0 is not in list
2. Then I use "pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp35-cp35m-linux_x86_64.whl", but it failed with "tensorflow-0.10.0rc0-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform."

HOW to fix it?

**Comment by orctyr** [comment]
conda install -c jjhelmus tensorflow=0.10.0rc0, it does not work.
@smaegol  If you can give me another source, that is also available. Many thanks!

**Comment by smaegol** [comment]
Which version of conda do you use? Do you install using `conda install -c smaegol plasflow` in the sourced separate environment? This should definitely work.

**Comment by orctyr** [comment]
Hi Smaegol,

Conda Version: 4.5.11

This command did not work:
conda install -c smaegol plasflow 


Best,


ORCTYR
 
From: Pawel Krawczyk
Date: 2018-09-28 21:17
To: smaegol/PlasFlow
CC: orctyr; Author
Subject: Re: [smaegol/PlasFlow] tensorflow=0.10.0rc0 Install Failed (#15)
Which version of conda do you use? Do you install using conda install -c smaegol plasflow in the sourced separate environment? This should definitely work.

**Comment by smaegol** [comment]
Ach, now I understand. You've tried to install PlasFlow in Windows and this is currently not possible (see platforms badge) as PlasFlow works only in UNIX-based systems (Linux, OSX). You should switch to any UNIX system to be able to use this software.
