### ISSUE TITLE
Plasflow running erro

### ISSUE THREAD

**Issue by BurinkiWU** [smaegol/PlasFlow#17]
Outputting fasta files with classified sequences
Traceback (most recent call last):
  File "/home/wzq/miniconda3/envs/plasflow/bin/PlasFlow.py", line 444, in <module>
    sequences_dict = SeqIO.index(args.inputfile, "fasta")
  File "/home/wzq/.local/lib/python3.5/site-packages/Bio/SeqIO/__init__.py", line 885, in index
    key_function, repr, "SeqRecord")
  File "/home/wzq/.local/lib/python3.5/site-packages/Bio/File.py", line 306, in __init__
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key '1034476d-0f96-4862-8f0e-aecb00f7cfcb'

Could you fix it ?
Thanks.

**Comment by smaegol** [comment]
Hi,

that error means that you have duplicated sequences in your dataset (or with the same ids). PlasFlow relies on sequence ids (taken from fasta header) to partition classified sequences into plasmid/chromosome/unclassified bins. You should deduplicate (or rename) your sequences. If those come from the nanopore sequencing (what I suppose from the ID) you probably mixed reads from different sequencing runs, so you can also analyze them separately

**Comment by BurinkiWU** [comment]
Hi,

Thanks for your information. 

I have already duplicated my sequences and all already have been done. However, I uploaded the result to NCBI to figure out the information of plasmid in details, and there were were nothing showed on NCBI blast result about plasmid. Are there something wrong about it ?

Thanks.

**Comment by smaegol** [comment]
Hi,

From what I understood, you've already done the classification using PlasFlow and got some plasmid results, but blast of plasmid sequences returns no plasmids, right? There can be multiple answers why is it like that:
1. PlasFlow, as every ML classifier is not perfect (estimated accuracy is >90%, depending on applied threshold), and sometimes returns wrong predictions. 
2. Your input sequences are too short, so there is not enough kmer coverage for proper classification
3. There are chimeras of chromosome/plasmid contigs and PlasFlow cannot clearly differentiate between them,
4. Analyzed sequence is novel (e.g. kmer signature completely different from what was used during training)
5. Input sequences are coming from organism other than Bacteria (PlasFlow was trained on bacterial sequences).
6. Sequences are too noisy for kmer-based analysis (I mean sequencing errors if not contigs but raw long reads (like nanopore) are used)

You can try to increase the threshold used for filtering, maybe it will help (but there will be less classified sequences in the output)
