### ISSUE TITLE
Running erro

### ISSUE THREAD

**Issue by BurinkiWU** [smaegol/PlasFlow#20]
$ PlasFlow.py --input filtered_seameta_trim_9.fasta --output seameta_trim_9.plasflow_predictions.tsv --threshold 0.7
/home/disk3-8T/wzq/miniconda3/lib/python3.5/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Failed with error:
  warnings.warn(x, RRuntimeWarning)
/home/disk3-8T/wzq/miniconda3/lib/python3.5/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning:
  warnings.warn(x, RRuntimeWarning)
/home/disk3-8T/wzq/miniconda3/lib/python3.5/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: ‘package ‘BiocGenerics’ 0.24.0 is loaded, but >= 0.25.3 is required by ‘IRanges’’
  warnings.warn(x, RRuntimeWarning)
/home/disk3-8T/wzq/miniconda3/lib/python3.5/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning:

  warnings.warn(x, RRuntimeWarning)
Importing sequences
Traceback (most recent call last):
  File "/home/disk3-8T/wzq/miniconda3/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 337, in __getattribute__
    return self.__getitem__(attr)
  File "/home/disk3-8T/wzq/miniconda3/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 342, in __getitem__
    res = _globalenv.get(item)
LookupError: 'readDNAStringSet' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/disk3-8T/wzq/miniconda3/bin/PlasFlow.py", line 93, in <module>
    input_data = r.readDNAStringSet(inputfile)
  File "/home/disk3-8T/wzq/miniconda3/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 339, in __getattribute__
    raise AttributeError(orig_ae)
AttributeError: 'R' object has no attribute 'readDNAStringSet'

**Comment by smaegol** [comment]
Make sure you have R installed (check with `which R` from the command line). If it is there, [BioStrings bioconductor package](https://bioconductor.org/packages/release/bioc/html/Biostrings.html) should be also installed as lack of it is the source of your problem. If you install from conda it should be already there. If it is still not there run R from the command line and install according to the instruction on the Biostrings website
