### ISSUE TITLE
tensorflow issue?

### ISSUE THREAD

**Issue by dgkurt** [smaegol/PlasFlow#23]
In a fresh installation of ubuntu 18.04.2 LTS, I installed miniconda and followed the plasflow conda installation. 
`conda -V`
> conda 4.6.12

Environment (`conda list`):

<details>
<summary>
Details
</summary>

> _r-mutex                  1.0.0               anacondar_1  
> bioconductor-biocgenerics 0.26.0                   r341_0    bioconda
> bioconductor-biostrings   2.48.0           r341h470a237_0    bioconda
> bioconductor-iranges      2.14.12          r341h470a237_0    bioconda
> bioconductor-s4vectors    0.18.3           r341h470a237_0    bioconda
> bioconductor-xvector      0.20.0           r341h470a237_0    bioconda
> bioconductor-zlibbioc     1.26.0           r341h470a237_0    bioconda
> biopython                 1.72                     py35_0    conda-forge
> blas                      1.0                         mkl  
> bzip2                     1.0.6             h14c3975_1002    conda-forge
> ca-certificates           2019.3.9             hecc5488_0    conda-forge
> cairo                     1.14.12           h80bd089_1005    conda-forge
> certifi                   2018.8.24             py35_1001    conda-forge
> curl                      7.61.0               h93b3f91_2    conda-forge
> fontconfig                2.13.1            he4413a7_1000    conda-forge
> freetype                  2.10.0               he983fc9_0    conda-forge
> gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
> glib                      2.56.2            had28632_1001    conda-forge
> graphite2                 1.3.13            hf484d3e_1000    conda-forge
> gsl                       2.2.1                h0c605f7_3  
> harfbuzz                  1.9.0             he243708_1001    conda-forge
> icu                       58.2              hf484d3e_1000    conda-forge
> intel-openmp              2019.3                      199  
> jpeg                      9c                h14c3975_1001    conda-forge
> krb5                      1.14.6                        0    conda-forge
> libffi                    3.2.1             he1b5a44_1006    conda-forge
> libgcc                    7.2.0                h69d50b8_2    conda-forge
> libgcc-ng                 8.2.0                hdf63c60_1  
> libgfortran               3.0.0                         1    conda-forge
> libgfortran-ng            7.3.0                hdf63c60_0  
> libiconv                  1.15              h516909a_1005    conda-forge
> libpng                    1.6.36            h84994c4_1000    conda-forge
> libprotobuf               3.6.0             hdbcaa40_1000    conda-forge
> libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
> libstdcxx-ng              8.2.0                hdf63c60_1  
> libtiff                   4.0.10            h648cc4a_1001    conda-forge
> libuuid                   2.32.1            h14c3975_1000    conda-forge
> libxcb                    1.13              h14c3975_1002    conda-forge
> libxml2                   2.9.8             h143f9aa_1005    conda-forge
> mkl                       2017.0.4             h4c4d0af_0  
> mock                      2.0.0                    py35_0    conda-forge
> ncurses                   6.1               hf484d3e_1002    conda-forge
> numpy                     1.11.3           py35h3dfced4_4  
> openssl                   1.0.2r               h14c3975_0    conda-forge
> pandas                    0.23.4           py35hf8a1672_0    conda-forge
> pango                     1.40.14           hf0c64fd_1003    conda-forge
> pbr                       5.1.3                      py_0    conda-forge
> pcre                      8.41              hf484d3e_1003    conda-forge
> pip                       18.0                  py35_1001    conda-forge
> pixman                    0.34.0            h14c3975_1003    conda-forge
> plasflow                  1.1.0                    py35_0    smaegol
> protobuf                  3.6.0            py35hfc679d8_0    conda-forge
> pthread-stubs             0.4               h14c3975_1001    conda-forge
> python                    3.5.5                h5001a0f_2    conda-forge
> python-dateutil           2.8.0                      py_0    conda-forge
> pytz                      2019.1                     py_0    conda-forge
> r-base                    3.4.1                h4fe35fd_8    conda-forge
> readline                  7.0               hf8c457e_1001    conda-forge
> rpy2                      2.8.5              py35r3.4.1_0    conda-forge
> scikit-learn              0.18.1              np111py35_1  
> scipy                     0.19.0              np111py35_0  
> setuptools                40.4.3                   py35_0    conda-forge
> six                       1.11.0                   py35_1    conda-forge
> sqlite                    3.26.0            h67949de_1001    conda-forge
> tensorflow                0.10.0rc0           np111py35_0  
> tk                        8.6.9             h84994c4_1001    conda-forge
> wheel                     0.32.0                py35_1000    conda-forge
> xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
> xorg-libice               1.0.9             h516909a_1004    conda-forge
> xorg-libsm                1.2.3             h84519dc_1000    conda-forge
> xorg-libx11               1.6.7             h14c3975_1000    conda-forge
> xorg-libxau               1.0.9                h14c3975_0    conda-forge
> xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
> xorg-libxext              1.3.4                h516909a_0    conda-forge
> xorg-libxrender           0.9.10            h516909a_1002    conda-forge
> xorg-libxt                1.1.5             h14c3975_1002    conda-forge
> xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
> xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
> xorg-xproto               7.0.31            h14c3975_1007    conda-forge
> xz                        5.2.4             h14c3975_1001    conda-forge
> zlib                      1.2.11            h14c3975_1004    conda-forge

</details>

The perl filter step went well, but when I run 
`PlasFlow.py --input scaffolds_filtered.fasta --output scaffolds.tsv`
I got the following error
> Importing sequences
> Imported  29  sequences
> Calculating kmer frequencies using kmer 5
> Transforming kmer frequencies
> Finished transforming, saving transformed values
> Traceback (most recent call last):
>   File "/home/dgkurt/miniconda3/envs/plasflow3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 52, in <module>
>     from tensorflow.core.framework.graph_pb2 import *
>   File "/home/dgkurt/miniconda3/envs/plasflow3/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
>     from google.protobuf import descriptor as _descriptor
>   File "/home/dgkurt/miniconda3/envs/plasflow3/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 47, in <module>
>     from google.protobuf.pyext import _message
> ImportError: /home/dgkurt/miniconda3/envs/plasflow3/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolEb
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/dgkurt/miniconda3/envs/plasflow3/bin/PlasFlow.py", line 346, in <module>
>     vote_proba = vote_class.predict_proba(inputfile)
>   File "/home/dgkurt/miniconda3/envs/plasflow3/bin/PlasFlow.py", line 300, in predict_proba
>     self.probas_ = [clf.predict_proba_tf(X) for clf in self.clfs]
>   File "/home/dgkurt/miniconda3/envs/plasflow3/bin/PlasFlow.py", line 300, in <listcomp>
>     self.probas_ = [clf.predict_proba_tf(X) for clf in self.clfs]
>   File "/home/dgkurt/miniconda3/envs/plasflow3/bin/PlasFlow.py", line 255, in predict_proba_tf
>     import tensorflow as tf
>   File "/home/dgkurt/miniconda3/envs/plasflow3/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
>     from tensorflow.python import *
>   File "/home/dgkurt/miniconda3/envs/plasflow3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 58, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "/home/dgkurt/miniconda3/envs/plasflow3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 52, in <module>
>     from tensorflow.core.framework.graph_pb2 import *
>   File "/home/dgkurt/miniconda3/envs/plasflow3/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
>     from google.protobuf import descriptor as _descriptor
>   File "/home/dgkurt/miniconda3/envs/plasflow3/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 47, in <module>
>     from google.protobuf.pyext import _message
> ImportError: /home/dgkurt/miniconda3/envs/plasflow3/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolEb
> 
> 
> Error importing tensorflow.  Unless you are using bazel,
> you should not try to import tensorflow from its source directory;
> please exit the tensorflow source tree, and relaunch your python interpreter
> from there.

**Comment by dgkurt** [comment]
I managed to solve this by downgrading protobuf to 3.0.0b2
`conda install protobuf==3.0.0b2`

**Comment by lalalagartija** [comment]
protobuf downgrading didn't work for me but this "conda install -c jjhelmus tensorflow=0.10.0rc0" worked eventhough I am on debian
