### ISSUE TITLE
WARNING: Logging before flag parsing goes to stderr.

### ISSUE THREAD

**Issue by wanjinhu** [smaegol/PlasFlow#35]
hello @smaegol 
when i run `PlasFlow.py --input test.fasta --output test_plasflow_predictions.tsv --threshold 0.7` , here are erro information:
`Finished transforming, saving transformed values
WARNING: Logging before flag parsing goes to stderr.
W1207 13:00:41.275060 140190885631808 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.`

can you help me out this problem?

**Also, another question from me is:** PlasFlow help us to identity which contig probably is belong to plasmid, now i have a plasmid fna file contain 35 contigs, can PlasFlow tell me which of these 35 contigs belong to the same Plasmid? Or just tell me these 35 contigs which are probably belong to plasmid or chom?

Thanks a lot

**Comment by smaegol** [comment]
Hi,

the first one is only a warning, it should not influence your results. Is the output produced?

The answer to the second question is simply: no. PlasFlow is the classifier which produces the strict output telling you if your sequence comes from a plasmid (and from which phyla) or not. It can't tell you if a given set of sequences comes from the same plasmid.

**Comment by wanjinhu** [comment]
Hi,
thanks for your reply, the first problem from me is not just a warning, no output result produced when that happens. 

can you figure it out?

**Comment by wanjinhu** [comment]
problem solved
