### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Timmywang1** [smaegol/PlasFlow#37]
Hello, 
smaegol 

When i running :
 PlasFlow.py --input /data/Timmy/Plasflow/filtered_ERR1051325.fa --output test.plasflow_predictions.tsv --threshold 0.7
Importing sequences
Imported  [1] 1100468
  sequences
Calculating kmer frequencies using kmer 5
Transforming kmer frequencies
Predicting labels using kmer 5  frequencies
Calculating kmer frequencies using kmer 6
**Segmentation fault (core dumped)**(error)

Is the running memory of my server too small?
Generally, how much memory is required to run this script?
Under my current server, is there any solution？

**Comment by smaegol** [comment]
Hi, yes, you can try to split your input sequences into smaller chunks, run they separately, and then merge results. It will not alter predictions any way.

**Comment by Timmywang1** [comment]
Thanks for your help, I have solved the above problem
**Another question:** 
These values（e.g., 0.01429714） represents probabilities of assignment，right？We should take a maximum value as the most likely classification？

chromosome.Acidobacteria | chromosome.Actinobacteria | chromosome.Bacteroidetes | chromosome.Chlamydiae | chromosome.Chlorobi | chromosome.Chloroflexi
-- | -- | -- | -- | -- | --
0.01429714 | 0.03409684 | 0.04466312 | 0.001745073 | 0.002053222 | 0.00560279
0.000204194 | 0.009454542 | 1.60E-06 | 4.10E-05 | 0.000118686 | 0.000226975
0.005880766 | 0.000460877 | 8.56E-07 | 0.001262039 | 0.00030829 | 0.006116112

**Comment by smaegol** [comment]
Yes, maximum value represents the most probable classification.

**Comment by JotaKas** [comment]
Hey @Timmywang1 ,

How did you solve your Segmentation fault (core dumped) problem?

Thanks in advance
