### ISSUE TITLE
filter_sequences_by_length.pl

### ISSUE THREAD

**Issue by Timmywang1** [smaegol/PlasFlow#38]
Hello,
Pawel
After running the script, I found my contigs leaving only those longer than 500 bp (not > 1000bp), I wonder if it is possible to customize the parameters, such as filtering short sequences with <1500bp, when i run 'filter_sequences_by_length.pl'.

**Comment by smaegol** [comment]
There is a -thresh option when invoking the script, which allows for any length threshold you wish
