### ISSUE TITLE
Installation issue on MacOS

### ISSUE THREAD

**Issue by yuxuanlan** [smaegol/PlasFlow#4]
Does the toolbox work on Mac?
While I was trying to install PlasFlow on a Mac I got the following error:
(plasflow) N82090:v1 lany$ conda install plasflow -c smaegol
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - plasflow

Current channels:

  - https://conda.anaconda.org/smaegol/osx-64
  - https://conda.anaconda.org/smaegol/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch

Many thanks,
Yuxuan

**Comment by smaegol** [comment]
In general it should, but was not tested. Therefore I haven't prepared separate channel for Mac but I will generate one after successful tests on Mac. For now, you can try to install the software manually, all dependencies are listed. 

Best,
Pawel

**Comment by smaegol** [comment]
New version of PlasFlow supports MacOs. Please see the updated installation instructions.
