### ISSUE TITLE
Installation Issues on MacOs and Windows

### ISSUE THREAD

**Issue by Sfinks123** [smaegol/PlasFlow#7]
Hi I was wondering if there is an update available to resolve the channels issue. I experienced the following during installation of MacOS:
<img width="695" alt="screen shot 2018-05-22 at 4 06 05 pm" src="https://user-images.githubusercontent.com/39506567/40394850-267e4cd8-5dda-11e8-80a1-e1d5a8ec207a.png">

Also, I experienced this during installation for Windows:

![capture](https://user-images.githubusercontent.com/39506567/40394715-71cf3284-5dd9-11e8-8509-c7e5a94b343d.JPG)

I also, tried installing PlasFlow manually and with no success. 

Many thanks for helping to resolve this issue,

-Sfinks

**Comment by smaegol** [comment]
The update, solving also memory problems, is in preparation and will be released (hopefully) till the end of the week. Keep in touch.

**Comment by smaegol** [comment]
New version of PlasFlow supports MacOs. Please see the updated installation instructions.
