### ISSUE TITLE
cannot locate bio/seqio.pm in @INC

### ISSUE THREAD

**Issue by imasianxd** [smaegol/PlasFlow#8]
Hi, I'm having trouble running the program with the following error. I think it's missing a perl module?
I installed the program using conda install plasflow -c smaegol.
Any advices?
Thanks for the assistance!

Can't locate Bio/SeqIO.pm in @INC (@INC contains: /home/jjjjia/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi /home/jjjjia/perl5/lib/perl5/5.16.3 /home/jjjjia/perl5/lib/perl5/x86_64-linux-thread-multi /home/jjjjia/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/jjjjia/.conda/envs/plasflow/bin/filter_sequences_by_length.pl line 24.
BEGIN failed--compilation aborted at /home/jjjjia/.conda/envs/plasflow/bin/filter_sequences_by_length.pl line 24.

**Comment by smaegol** [comment]
Hi,

I updated requirements part of the manual, including dependencies for perl scripts. You're right, perl modules are missing, which are required to run filter_sequences_by_length.pl. There are several ways to install them. You can use package manager of your system (apt,brew), cpan or, easy-way, conda. Please see details in the updated manual. Sorry for not including that before.

**Comment by stevenjdunn** [comment]
If installing in an environment the error still shows after installing the perl dependencies via Conda. You'll need to edit the shebang in your favourite text editor to reflect the location of your perl install:

    which perl # Shows perl install path
    which filter_sequences_by_length.pl # Shows location of script
The shebang before:

    #!/usr/bin/perl
After:

    #!/usr/miniconda/envs/environment/bin/perl

Or alternatively manually invoke the scripts using for e.g:
    
    perl /home/user/miniconda/envs/environment/bin/filter_sequences_by_length.pl

**Comment by smaegol** [comment]
> The shebang before:
> 
> ```
> #!/usr/bin/perl
> ```
> 
> After:
> 
> ```
> #!/usr/miniconda/envs/environment/bin/perl
> ```

Alternatively set shebang like that:

```
#!/usr/bin/env perl
```

This will automatically choose the perl binary available in the path

**Comment by LuoDaTou123** [comment]
conda install snippy >snippy 3.1   run error
github clone snippy>snippy 4.6 run ok
here:
git clone https://github.com/tseemann/snippy.git

You'll need to add Snippy's bin directory to your $PATH

maybe conda snippy is old version not upgrade
